# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: scd4x

before:
  hooks:
    - go mod tidy

builds:
  - id: monitor
    main: ./examples/monitor
    binary: scd4x-monitor
    env:
      - CGO_ENABLED=0
      - GOWORK=off
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: signal_compensation
    main: ./examples/signal_compensation
    binary: scd4x-signal-compensation
    env:
      - CGO_ENABLED=0
      - GOWORK=off
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^Merge pull request"
      - "^Merge branch"

release:
  name_template: "v{{ .Version }}"
